#! /bin/sh

if ! command -v docker >/dev/null 2>&1; then
    echo "Error: Docker is not installed. Please install Docker and try again."
    echo "Visit https://docs.docker.com/get-docker/ for installation instructions."
    exit 1
fi

if ! (id -nG "$USER" | grep -qw docker); then
    echo "Error: User '$USER' is not in the 'docker' group. Please add the user to the docker group and try again."
    echo "You can do this by running: sudo usermod -aG docker \$USER."
    echo "After this, log out and log back in for the changes to take effect."
    exit 1
fi

tmpfile=$(mktemp)
env | grep -iE 'DEBUG|NODE_|ELECTRON_|YARN_|NPM_|CI|CIRCLE|TRAVIS_TAG|TRAVIS|TRAVIS_REPO_|TRAVIS_BUILD_|TRAVIS_BRANCH|TRAVIS_PULL_REQUEST_|APPVEYOR_|CSC_|GH_|GITHUB_|BT_|AWS_|STRIP|BUILD_' > "$tmpfile"

docker run --rm -ti --env-file="$tmpfile" --env ELECTRON_CACHE="/root/.cache/electron" --env ELECTRON_BUILDER_CACHE="/root/.cache/electron-builder" -v ~/.gitconfig:/etc/gitconfig -v ${PWD}:/project -v ${PWD##*/}-node-modules:/project/node_modules -v ~/.cache/electron:/root/.cache/electron -v ~/.cache/electron-builder:/root/.cache/electron-builder electronuserland/builder:wine
